### ISSUE TITLE
建议能影响pybroker升级pandas

### ISSUE THREAD

**Issue by skywolf123** [akfamily/akbroker#1]
akshare提示
D:\miniconda3\envs\quant\Lib\site-packages\akshare\__init__.py:2609: UserWarning: 为了支持更多特性，请将 Pandas 升级到 2.1.0 及以上版本！

而pybroker需要<2的pandas版本
lib-pybroker 1.1.29 requires pandas<2,>=1.5.1

直接使用新版的pandas，pybroker会报错，比如：
  File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 1060, in backtest
    return self.walkforward(
           ^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 1211, in walkforward
    self._run_walkforward(
  File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 1282, in _run_walkforward
    for train_idx, test_idx in self.walkforward_split(
  File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 648, in walkforward_split
    window_dates.sort()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'DatetimeArray' object has no attribute 'sort'

建议能影响pybroker升级pandas依赖版本

**Comment by albertandking** [comment]
> akshare提示 D:\miniconda3\envs\quant\Lib\site-packages\akshare__init__.py:2609: UserWarning: 为了支持更多特性，请将 Pandas 升级到 2.1.0 及以上版本！
> 
> 而pybroker需要<2的pandas版本 lib-pybroker 1.1.29 requires pandas<2,>=1.5.1
> 
> 直接使用新版的pandas，pybroker会报错，比如： File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 1060, in backtest return self.walkforward( ^^^^^^^^^^^^^^^^^ File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 1211, in walkforward self._run_walkforward( File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 1282, in _run_walkforward for train_idx, test_idx in self.walkforward_split( File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 648, in walkforward_split window_dates.sort() ^^^^^^^^^^^^^^^^^ AttributeError: 'DatetimeArray' object has no attribute 'sort'
> 
> 建议能影响pybroker升级pandas依赖版本

已经在处理了，近期会升级到 pandas 2.0 以上版本

**Comment by albertandking** [comment]
目前会在第三方依赖库兼容 Pandas 2.0 以上版本后升级

**Comment by albertandking** [comment]
> akshare提示 D:\miniconda3\envs\quant\Lib\site-packages\akshare__init__.py:2609: UserWarning: 为了支持更多特性，请将 Pandas 升级到 2.1.0 及以上版本！
> 
> 而pybroker需要<2的pandas版本 lib-pybroker 1.1.29 requires pandas<2,>=1.5.1
> 
> 直接使用新版的pandas，pybroker会报错，比如： File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 1060, in backtest return self.walkforward( ^^^^^^^^^^^^^^^^^ File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 1211, in walkforward self._run_walkforward( File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 1282, in _run_walkforward for train_idx, test_idx in self.walkforward_split( File "D:\miniconda3\envs\quant\Lib\site-packages\pybroker\strategy.py", line 648, in walkforward_split window_dates.sort() ^^^^^^^^^^^^^^^^^ AttributeError: 'DatetimeArray' object has no attribute 'sort'
> 
> 建议能影响pybroker升级pandas依赖版本

目前最新版本已经支持 pandas 2.0
